using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CppSharp;
using CppSharp.AST;
using CppSharp.Types.Std.CLI;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Shouldly;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static Microsoft.CodeAnalysis.CSharp.SyntaxKind;
using Attribute = CppSharp.AST.Attribute;
using CallingConvention = CppSharp.AST.CallingConvention;
using Delegate = CppSharp.AST.Delegate;
using Type = CppSharp.AST.Type;

namespace ShaderSlang.Net.Scripts.CppSharpGenerator;

/// <summary>
/// Convenience methods to create Roslyn syntax nodes from CppSharp AST nodes, to be used in the code generator.
/// By design, they will be kept as simple as possible and will not attempt to handle complex scenarios or edge cases, the code generator should be responsible for modifying the AST to fit the expected input of these methods.
/// For example, the input ast node should already have the necessary attributes for the generated code, and these methods will just convert them to syntax nodes without adding any additional logic or attributes.
/// This means the input AST for these methods should already be well-formed and as close as possible to the final AST that we want to generate.
/// Any necessary modifications or adjustments should be done in the code generator or passes before calling these methods.
/// </summary>
[SuppressMessage("ReSharper", "MemberCanBePrivate.Global")]
internal static class AstToSyntaxFactory
{
    public static SyntaxTriviaList CreateAutoGeneratedCommentTrivia()
    {
        return TriviaList(Comment("// ----------------------------------------------------------------------------"),
                          Comment("// <auto-generated>"),
                          Comment("// This is autogenerated code by CppSharp."),
                          Comment("// Do not edit this file or all your changes will be lost after re-generation."),
                          Comment("// </auto-generated>"),
                          Comment("// ----------------------------------------------------------------------------"));
    }

    public static UsingDirectiveSyntax CreateUsingDirectiveFrom(Type type)
    {
        var name = type.ToString();
        return UsingDirective(ParseName(name));
    }

    public static UsingDirectiveSyntax CreateUsingDirectiveFrom(params ReadOnlySpan<string> parts)
    {
        return UsingDirective(CreateNameFromParts(parts));
    }

    public static UsingDirectiveSyntax CreateUsingDirectiveGlobalFrom(params ReadOnlySpan<string> parts)
    {
        var dir = UsingDirective(CreateNameFromParts(parts));

        var globalName = IdentifierName(Token(GlobalKeyword));
        var firstIdentifier = dir.DescendantNodes().OfType<IdentifierNameSyntax>().First();

        return dir.ReplaceNode(firstIdentifier, AliasQualifiedName(globalName, firstIdentifier));
    }

    public static UsingDirectiveSyntax CreateUsingAliasFrom(string aliasName, params ReadOnlySpan<string> parts)
    {
        return UsingDirective(CreateNameFromParts(parts)).WithAlias(NameEquals(IdentifierName(aliasName)));
    }

    public static UsingDirectiveSyntax CreateUsingAliasGlobalFrom(string aliasName, params ReadOnlySpan<string> parts)
    {
        var dir = UsingDirective(CreateNameFromParts(parts)).WithAlias(NameEquals(IdentifierName(aliasName)));

        var globalName = IdentifierName(Token(GlobalKeyword));
        var firstIdentifier = dir.Name!.DescendantNodes().OfType<IdentifierNameSyntax>().First();

        return dir.ReplaceNode(firstIdentifier, AliasQualifiedName(globalName, firstIdentifier));
    }

    public static SyntaxTrivia CreatePragmaWarningDisableTriviaFrom(string errorCode, string comment = "")
    {
        comment = comment.StartsWith("//") ? comment : $"// {comment}";

        return Trivia(PragmaWarningDirectiveTrivia(Token(DisableKeyword), true)
                          .WithErrorCodes([IdentifierName(Identifier([], errorCode, TriviaList(Comment(comment))))]));
    }

    public static NamespaceDeclarationSyntax CreateNamespaceDeclarationFrom(Namespace @namespace)
    {
        var namespaceDecl = NamespaceDeclaration(ParseName(@namespace.Name));

        if (@namespace.Comment is not null)
        {
            namespaceDecl = namespaceDecl.WithDocumentationFrom(@namespace);
        }

        return namespaceDecl;
    }

    public static SyntaxTrivia CreateDocumentationTriviaFrom(Comment comment)
    {
        var visitor = new CommentVisitor();
        var result = visitor.Visit(comment);
        if (result is DocumentationCommentTriviaSyntax docTrivia) return Trivia(docTrivia);

        return Trivia(DocumentationCommentTrivia(SingleLineDocumentationCommentTrivia,
                                                 List<XmlNodeSyntax>([
                                                     XmlText(XmlTextLiteral(result?.ToString() ?? string.Empty))
                                                 ])));
    }

    public static AttributeSyntax CreateAttributeSyntaxFrom(Attribute attribute)
    {
        var attributeName = attribute.Type.ToGlobalFullName().Replace("Attribute", "");
        var attributeArgs = ParseAttributeArgumentList($"({attribute.Value})");
        return Attribute(ParseName(attributeName), attributeArgs);
    }

    public static EnumMemberDeclarationSyntax CreateEnumMemberFrom(Enumeration.Item enumItem)
    {
        var member = EnumMemberDeclaration(enumItem.Name);
        if (enumItem.ExplicitValue)
        {
            member = member.WithEqualsValue(
                EqualsValueClause(LiteralExpression(NumericLiteralExpression, Literal((int)enumItem.Value))));
        }
        else
        {
            Diagnostics.Error("Expression enum items are not supported yet.");
        }

        if (enumItem.Comment is not null)
        {
            member = member.WithDocumentationFrom(enumItem);
        }

        return member;
    }

    public static EnumDeclarationSyntax CreateEnumDeclarationFrom(Enumeration cppEnum)
    {
        var enumMembers = cppEnum.Items.Select(CreateEnumMemberFrom);

        var enumDecl = EnumDeclaration(cppEnum.Name)
                       .AddModifiers(cppEnum.Access.ToToken())
                       .WithDocumentationFrom(cppEnum)
                       .WithBaseList(
                           BaseList(SingletonSeparatedList<BaseTypeSyntax>(
                                        SimpleBaseType(IdentifierName(cppEnum.BuiltinType.ToString())))))
                       .WithMembers(SeparatedList(enumMembers,
                                                  Enumerable.Repeat(Token(CommaToken),
                                                                    Math.Max(0, cppEnum.Items.Count - 1))));

        return enumDecl;
    }

    public static AttributeListSyntax[] CreateAttributeListsFrom(Declaration decl)
    {
        var attributeSyntaxLists = new List<AttributeListSyntax>();
        
        var retAttributes = decl.Attributes.OfType<ReturnAttribute>().ToArray();
        var normalAttributes = decl.Attributes.Except(retAttributes).ToArray();

        if(retAttributes.Length > 0)
        {
            attributeSyntaxLists.Add(AttributeListToReturnTarget(AttributeList([..retAttributes.Select(CreateAttributeSyntaxFrom)])));
        }

        if (normalAttributes.Length > 0)
        {
            attributeSyntaxLists.Add(AttributeList([..normalAttributes.Select(CreateAttributeSyntaxFrom)]));
        }
        
        return attributeSyntaxLists.ToArray();

        static AttributeListSyntax AttributeListToReturnTarget(AttributeListSyntax attributeListSyntax)
        {
            return attributeListSyntax.WithTarget(AttributeTargetSpecifier(Token(ReturnKeyword)).WithTrailingTrivia(Space));
        }
    }

    public static ParameterSyntax CreateParameterFrom(Parameter parameter)
    {
        return Parameter(Identifier(parameter.Name))
               .WithType(parameter.Type.ToSyntax())
               .AddAttributeLists(CreateAttributeListsFrom(parameter).ToArray())
               .WithDocumentationFrom(parameter);
    }

    public static ParameterListSyntax CreateParameterListFrom(params IEnumerable<Parameter> parameters)
    {
        var paramSyntax = parameters.Select(CreateParameterFrom);
        
        return ParameterList(SeparatedList(paramSyntax));
    }

    //TODO: move in code generator
    public static AttributeSyntax? CreateCallingConventionAttribute(CallingConvention callingConvention)
    {
        var callconvType = callingConvention switch
        {
            CallingConvention.C => typeof(CallConvCdecl),
            CallingConvention.StdCall => typeof(CallConvStdcall),
            CallingConvention.ThisCall => typeof(CallConvThiscall),
            CallingConvention.FastCall => typeof(CallConvFastcall),
            _ => null
        };
        
        if(callconvType is null) return null;

        var astAttribute = new Attribute
        {
            Type = callconvType,
            Value = $"CallConvs = [typeof({callconvType.ToGlobalFullName()}])"
        };
        
        return CreateAttributeSyntaxFrom(astAttribute);
    }

    public static DelegateDeclarationSyntax CreateDelegateFrom(Delegate decl)
    {
        var returnType = decl.Type.ReturnType.ToSyntax();
        var parameters = CreateParameterListFrom(decl.Type.Parameters);


        var delegateSyntax = DelegateDeclaration(returnType, decl.Name)
                             .WithDocumentationFrom(decl)
                             .AddAttributeLists(CreateAttributeListsFrom(decl))
                             .WithParameterList(parameters);

        //TODO: decide if we keep this here or if we prefer moving it to code generator and modify the AST directly
        if (decl.Type.CallingConvention is CallingConvention.Default or CallingConvention.Unknown)
            return delegateSyntax;
        var callingConventionAttribute = CreateCallingConventionAttribute(decl.Type.CallingConvention);

        if (callingConventionAttribute is not null)
            return delegateSyntax.AddAttributeLists(AttributeList(null, [callingConventionAttribute]));
        
        Diagnostics.Warning($"Unsupported calling convention '{decl.Type.CallingConvention}' on delegate '{decl.Name}', no attribute will be generated for it.");
        return delegateSyntax;
    }

    /// <summary>
    /// Creates a MethodDeclarationSyntax from an AST node with that same signature.
    /// </summary>
    /// <remarks>The body of the method is NOT generated</remarks>
    /// <param name="function">The AST node to generate the method for</param>
    /// <returns></returns>
    public static MethodDeclarationSyntax CreateMethodFrom(Function function)
    {
        var returnType = function.ReturnType.ToSyntax();
        var parameters = CreateParameterListFrom(function.Parameters);

        var methodSyntax = MethodDeclaration(returnType, function.Name)
                           .WithDocumentationFrom(function)
                           .AddAttributeLists(CreateAttributeListsFrom(function))
                           .WithParameterList(parameters)
                           .AddModifiers(function.Access.ToToken());

        return methodSyntax;
    }


    public static TypeDeclarationSyntax CreateTypeDeclarationFrom(Class decl)
    {
        TypeDeclarationSyntax typeSyntax = decl.IsValueType ? StructDeclaration(decl.Name) 
            : decl.IsInterface ? InterfaceDeclaration(decl.Name) : ClassDeclaration(decl.Name);

        typeSyntax = typeSyntax.WithDocumentationFrom(decl)
                               .AddAttributeLists(CreateAttributeListsFrom(decl))
                               .AddModifiers(decl.Access.ToToken());

        if (decl.HasBase)
        {
            var baseTypesSyntax = decl.Bases
                                      .Where(b => b.IsGenerated)
                                      .Select(b => SimpleBaseType(b.Type.ToSyntax()));
            
            typeSyntax = typeSyntax.WithBaseList(BaseList([..baseTypesSyntax]));
        }
        
        if (decl.IsStatic)
        {
            typeSyntax = typeSyntax.AddModifiers(Token(StaticKeyword));
        }

        if (decl.IsAbstract && !decl.IsStatic)
        {
            typeSyntax = typeSyntax.AddModifiers(Token(AbstractKeyword));
        }

        return typeSyntax.AddModifiers(Token(PartialKeyword));
    }

    internal static NameSyntax CreateNameFromParts(params ReadOnlySpan<string> parts)
    {
        parts.Length.ShouldNotBe(0, "At least one part is required for a name syntax");

        NameSyntax name = IdentifierName(parts[0]);

        for (var i = 1; i < parts.Length; i++)
        {
            name = QualifiedName(name, IdentifierName(parts[i]));
        }

        return name;
    }

    private sealed class CommentVisitor : ICommentVisitor<SyntaxNode?>
    {
        public SyntaxNode? Visit(Comment comment) =>
            comment switch
            {
                // Derived types of BlockCommandComment must come before it
                VerbatimBlockComment c => VisitVerbatimBlock(c),
                VerbatimLineComment c => VisitVerbatimLine(c),
                ParamCommandComment c => VisitParamCommand(c),
                TParamCommandComment c => VisitTParamCommand(c),
                // Base types
                BlockCommandComment c => VisitBlockCommand(c),
                VerbatimBlockLineComment c => VisitVerbatimBlockLine(c),
                ParagraphComment c => VisitParagraph(c),
                TextComment c => VisitText(c),
                InlineCommandComment c => VisitInlineCommand(c),
                HTMLStartTagComment c => VisitHTMLStartTag(c),
                HTMLEndTagComment c => VisitHTMLEndTag(c),
                FullComment c => VisitFull(c),
                _ => null,
            };

        // "/// " prefix token — exterior trivia on the text literal, space as value
        private static XmlTextSyntax XmlExteriorText() =>
            XmlText(XmlTextLiteral(TriviaList(DocumentationCommentExterior("///")), " ", " ", TriviaList()));

        // Newline between doc comment lines
        private static XmlTextSyntax XmlNewlineText() =>
            XmlText(XmlTextNewLine(TriviaList(), Environment.NewLine, Environment.NewLine, TriviaList()));

        private static XmlElementSyntax MakeElement(string tag, IEnumerable<XmlNodeSyntax> children)
        {
            var name = XmlName(tag);
            return XmlElement(XmlElementStartTag(name), List(children), XmlElementEndTag(name));
        }

        private static XmlElementSyntax MakeElement(string tag,
                                                    IEnumerable<XmlAttributeSyntax> attrs,
                                                    IEnumerable<XmlNodeSyntax> children)
        {
            var name = XmlName(tag);
            return XmlElement(XmlElementStartTag(name).WithAttributes(List(attrs)), List(children), XmlElementEndTag(name));
        }

        private List<XmlNodeSyntax> VisitContent(ParagraphComment paragraph)
        {
            var nodes = new List<XmlNodeSyntax>();
            foreach (var inline in paragraph.Content)
                if (Visit(inline) is XmlNodeSyntax n)
                    nodes.Add(n);
            return nodes;
        }

        // -----------------------------------------------------------------------
        // ICommentVisitor<SyntaxNode?>
        // -----------------------------------------------------------------------

        public SyntaxNode? VisitText(TextComment comment)
        {
            var text = (comment.Text ?? string.Empty).Trim('\r', '\n');
            return XmlText(XmlTextLiteral(text));
        }

        public SyntaxNode? VisitParagraph(ParagraphComment comment)
        {
            var children = VisitContent(comment);
            // Return just text content; wrapping in <para> is decided by the parent context
            return children.Count == 0 ? null : children.Count == 1 ? children[0] : MakeElement("para", children);
        }

        public SyntaxNode? VisitBlockCommand(BlockCommandComment comment)
        {
            var tag = comment.CommandKind switch
            {
                CommentCommandKind.Brief => "summary",
                CommentCommandKind.Returns or CommentCommandKind.Return => "returns",
                CommentCommandKind.Note or CommentCommandKind.Remarks => "remarks",
                CommentCommandKind.Throws or CommentCommandKind.Throw => "exception",
                CommentCommandKind.See or CommentCommandKind.Sa => "seealso",
                _ => "remarks",
            };

            var children = comment.ParagraphComment is { } para ? VisitContent(para) : [];
            if (children.Count == 0) children.Add(XmlText(XmlTextLiteral(string.Empty)));

            return MakeElement(tag, children);
        }

        public SyntaxNode? VisitParamCommand(ParamCommandComment comment)
        {
            // Param name is stored in BlockCommandComment.Arguments[0].Text
            var paramName = comment.Arguments.Count > 0 ? comment.Arguments[0].Text ?? string.Empty : string.Empty;
            var children = comment.ParagraphComment is { } para ? VisitContent(para) : [];
            if (children.Count == 0) children.Add(XmlText(XmlTextLiteral(string.Empty)));

            return MakeElement("param", [XmlTextAttribute("name", paramName)], children);
        }

        public SyntaxNode? VisitTParamCommand(TParamCommandComment comment)
        {
            // Template param name is stored in BlockCommandComment.Arguments[0].Text
            var paramName = comment.Arguments.Count > 0 ? comment.Arguments[0].Text ?? string.Empty : string.Empty;
            var children = comment.ParagraphComment is { } para ? VisitContent(para) : [];
            if (children.Count == 0) children.Add(XmlText(XmlTextLiteral(string.Empty)));

            return MakeElement("typeparam", [XmlTextAttribute("name", paramName)], children);
        }

        public SyntaxNode? VisitVerbatimBlock(VerbatimBlockComment comment)
        {
            var text = string.Join(Environment.NewLine, comment.Lines.Select(l => l.Text ?? string.Empty));
            return MakeElement("code", [XmlText(XmlTextLiteral(text))]);
        }

        public SyntaxNode? VisitVerbatimBlockLine(VerbatimBlockLineComment comment) =>
            XmlText(XmlTextLiteral(comment.Text ?? string.Empty));

        public SyntaxNode? VisitVerbatimLine(VerbatimLineComment comment)
        {
            // VerbatimLineComment extends BlockCommandComment; Text holds the verbatim content
            var text = comment.Text?.Trim() ?? string.Empty;
            var name = XmlName("c");
            return XmlElement(XmlElementStartTag(name),
                              SingletonList<XmlNodeSyntax>(XmlText(XmlTextLiteral(text))),
                              XmlElementEndTag(name));
        }

        public SyntaxNode? VisitHTMLStartTag(HTMLStartTagComment comment)
        {
            var tagName = comment.TagName ?? "span";
            var attrs = comment.Attributes.Select(a => (XmlAttributeSyntax)XmlTextAttribute(a.Name, a.Value)).ToList();

            if (comment.SelfClosing) return XmlEmptyElement(XmlName(tagName)).WithAttributes(List(attrs));

            // Unpaired open tag — emit as raw text
            var attrStr = attrs.Count > 0
                ? " " + string.Join(" ", comment.Attributes.Select(a => $"{a.Name}=\"{a.Value}\""))
                : string.Empty;
            return XmlText(XmlTextLiteral($"<{tagName}{attrStr}>"));
        }

        public SyntaxNode? VisitHTMLEndTag(HTMLEndTagComment comment) =>
            XmlText(XmlTextLiteral($"</{comment.TagName ?? "span"}>"));

        public SyntaxNode? VisitInlineCommand(InlineCommandComment comment)
        {
            var arg = comment.Arguments.Count > 0 ? comment.Arguments[0].Text ?? string.Empty : string.Empty;

            // Use RenderKind to determine formatting intent instead of command name string
            var xmlTag = comment.CommentRenderKind switch
            {
                InlineCommandComment.RenderKind.RenderBold => "b",
                InlineCommandComment.RenderKind.RenderMonospaced => "c",
                InlineCommandComment.RenderKind.RenderEmphasized => "em",
                _ => "c",
            };

            var name = XmlName(xmlTag);
            return XmlElement(XmlElementStartTag(name),
                              SingletonList<XmlNodeSyntax>(XmlText(XmlTextLiteral(arg))),
                              XmlElementEndTag(name));
        }

        public SyntaxNode? VisitFull(FullComment comment)
        {
            var xmlNodes = new List<XmlNodeSyntax>();

            var blocks = comment.Blocks.Select(b => (block: b, node: Visit(b))).Where(t => t.node is XmlNodeSyntax).ToList();

            if (blocks.Count == 0) return DocumentationCommentTrivia(SingleLineDocumentationCommentTrivia, List(xmlNodes));

            void AppendBlock(XmlNodeSyntax node)
            {
                if (xmlNodes.Count > 0) xmlNodes.Add(XmlNewlineText());
                xmlNodes.Add(XmlExteriorText());
                xmlNodes.Add(node);
            }

            if (blocks.Count == 1 && blocks[0].block is ParagraphComment)
            {
                AppendBlock(MakeElement("summary", [(XmlNodeSyntax)blocks[0].node!]));
            }
            else
            {
                var first = blocks[0];
                if (first.block is ParagraphComment)
                {
                    AppendBlock(MakeElement("summary", [(XmlNodeSyntax)first.node!]));
                    foreach (var (_, node) in blocks.Skip(1)) AppendBlock((XmlNodeSyntax)node!);
                }
                else
                {
                    foreach (var (_, node) in blocks) AppendBlock((XmlNodeSyntax)node!);
                }
            }

            xmlNodes.Add(XmlNewlineText());

            return DocumentationCommentTrivia(SingleLineDocumentationCommentTrivia, List(xmlNodes));
        }
    }
}