name: ci

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-quality: 'preview'
          global-json-file: "./global.json"
      
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      
      - name: 'Run: Compile, RunTests'
        run: dotnet run --project ./build/_build.csproj -- Compile RunTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
